### ISSUE TITLE
EDP fix: Comparative analysis address

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#455] opened 2016-05-09 08:37 UTC
Comparison "Take me to comparative analysis of data platforms", https://how-to.usopendata.org/basics/data-repositories.html (address should be changed to https://how-to.usopendata.org/en/latest/The-Basics-of-Open-Data/Data-Repositories/)

**Comment by davetaz** [comment] 2016-05-10 08:17
duplicate of  #438

**Closed as completed by davetaz** 2016-05-10 08:17 UTC
Labels: Module 8
