### ISSUE TITLE
EDP fix: Open Gov fix

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#451] opened 2016-05-09 08:28 UTC
In Open government licences
Take me to the French Government open licence, http://wiki.data.gouv.fr/wiki/Licence_Ouverte_/_Open_Licence  
the link should lead to http://wiki.data.gouv.fr/wiki/Licence_Ouverte_/_Open_Licence  but it redirects to http://www.data.gouv.fr/fr/faq/
http://www.europeandataportal.eu/elearning/en/module8/#/id/co-01

**Comment by davetaz** [comment] 2016-05-10 08:18
duplicate of #439

**Closed as completed by davetaz** 2016-05-10 08:18 UTC
Labels: Module 4
