### ISSUE TITLE
EDP Benefits of open data - broken link

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#449] opened 2016-05-09 08:26 UTC
Benefits of open data licensing section :
Providing Clarity  (2nd slider), http://www.opendatamonitor.eu/frontend/web/index.php?r=datacatalogue%2Findex
the link is broken, error message : "Missing required parameters: id"

**Comment by davetaz** [comment] 2016-05-10 08:19
duplicate of #439

**Closed as completed by davetaz** 2016-05-10 08:19 UTC
Labels: Module 4
