### ISSUE TITLE
EDP fix: Simple licences, easily found links

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#450] opened 2016-05-09 08:27 UTC
Simple licences, easily found section:
Singapore Government (2nd slider), http://data.gov.sg/Metadata/OneMapMetadata.aspx?id=DENGUE_CLUSTER&t=SPATIAL
the link is broken: Error 404

**Comment by davetaz** [comment] 2016-05-10 08:19
duplicate of #439

**Closed as completed by davetaz** 2016-05-10 08:19 UTC
Labels: Module 4
