### ISSUE TITLE
Questions not showing in module 13

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#490] opened 2016-08-09 08:28 UTC
![screen shot 2016-07-29 at 21 49 04](https://cloud.githubusercontent.com/assets/10268640/17509772/a222f76c-5e13-11e6-90e2-2435ac9a9823.png)

**Comment by davetaz** [comment] 2016-08-10 12:46
Duplicate of #353

**Closed as completed** 2016-08-10 15:36 UTC
Labels: Module 13
