### ISSUE TITLE
EDP: data catalogs address

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#454] opened 2016-05-09 08:35 UTC
Under "Open data platform design approaches" Data catalogs: "Take me to Amsterdam CKAN portal", www.amsterdamopendata.nl/home (address should be changed to http://data.amsterdam.nl)

**Comment by davetaz** [comment] 2016-05-10 08:17
duplicate of #438

**Closed as completed by davetaz** 2016-05-10 08:17 UTC
Labels: Module 8
